sonar.projectKey=oaknational_oak-resource-adapter
sonar.organization=oaknational
sonar.projectName=oak-resource-adapter

sonar.sources=apps,packages
sonar.exclusions=**/dist/**,**/generated/**,**/.next/**,**/coverage/**,**/*.d.ts
sonar.tests=apps,packages
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/sentry.*.config.ts
sonar.coverage.exclusions=**/sentry.*.config.ts,**/instrumentation.ts,**/next.config.ts,**/vitest.setup.ts
sonar.javascript.lcov.reportPaths=apps/**/coverage/lcov.info,packages/**/coverage/lcov.info
